### PR TITLE
Iss prismatic joint

### PR DESCRIPTION
**Pull request by bkocev**
Added support for setting the values of prismatic joints.

### CODE REVIEW

**Comment by Rauldg** [comment]
@bkocev 

At first sight, why are there so many commits in this PR? 

Seems like you are introducing much more changes than just "Added support for setting the values of prismatic joints." Maybe is this PR actually intended to target other repo?

**Comment by planthaber** [comment]
looks like i mixed up the branches when telling him the destination.

Can you change it to the "devel" branch?

**Comment by bkocev** [comment]
Changed it to the "devel" branch.

**Comment by Rauldg** [comment]
I don't have any current project to test.

The code looks fine.

@planthaber feel free to merge if it is tested.

**Pull request merged**
